### ISSUE TITLE
Página CETC2016 - Correção de gralhas de texto

### ISSUE THREAD

**Issue by arturj** [cetc2016/cetc2016.github.io#1]
Sugestões de Correção:

0- "Inportant Dates" -> "Important Dates"

1 - Na secção "Contacts" e na secção "Previous Editions" ainda está CETC2013; deverá ser CETC2016.

2 - O primeira entrada da barra de menu não deveria ser "CETC2016", pois repete o texto acima.
O texto da primeira entrada poderia ser "Welcome" que está no dropdown menu assoicado.

7 - O texto das "Previous Editions":  ""CETC2013 is the second edition of the....." deverá ser atualizado para a CETC2016.

8- No texto da "Venue" : "PUBLIC TRANSPORT" -> "PUBLIC TRANSPORTATION"

**Comment by fmcarvalho** [comment]
@arturj Os pontos 0, 1, 2, 7 e 8 foram corrigidos. Confirma sff.

No ponto 2 A primeira entrada da barra de menu passou a Home à semelhança do cetc 2013.

Os restantes pontos vou passar para outros Issues.

**Comment by fmcarvalho** [comment]
@arturj @cvaz @ruimfjesus  Confirmem. Se estiver OK, fecho este issue.

**Comment by ruimfjesus** [comment]
Olá,

O ponto 0 ainda não está. Os outros já confirmei.
Rui Jesus

On Wed, Mar 11, 2015 at 3:44 PM, Fernando Miguel Carvalho <
notifications@github.com> wrote:

> @arturj https://github.com/arturj @cvaz https://github.com/cvaz
> @ruimfjesus https://github.com/ruimfjesus Confirmem. Se estiver OK,
> fecho este issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetc2016/cetc2016.github.io/issues/1#issuecomment-78289624
> .

## 

Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219

**Comment by fmcarvalho** [comment]
Ok, corrigi novamente o ponto 0.

**Comment by ruimfjesus** [comment]
Agora sim, confirmo.

On Wed, Mar 11, 2015 at 4:11 PM, Fernando Miguel Carvalho <
notifications@github.com> wrote:

> Ok, corrigi novamente o ponto 0.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetc2016/cetc2016.github.io/issues/1#issuecomment-78295718
> .

## 

Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219

**Comment by cvaz** [comment]
Olá,

também confirmo.

Cátia
