### ISSUE TITLE
Os sponsors que estão na barra lateral

### ISSUE THREAD

**Issue by cvaz** [cetc2016/cetc2016.github.io#10]
É necessário retirar as o google a afins como sponsors

**Comment by fmcarvalho** [comment]
E fica vazio???? Não coseguiremos assegurar já alguns patrocínios?

**Comment by cvaz** [comment]
Sim, quanto muito com o símbolo do ISEL.

Cátia

**Comment by fmcarvalho** [comment]
Já substitui os dummys pelo ISEL e IPL
