### ISSUE TITLE
Página CETC2016- Sugestões de melhoria gráfica e visual

### ISSUE THREAD

**Issue by arturj** [cetc2016/cetc2016.github.io#4]
Sugestões de Melhoria:

1 - Colocar as imagem a mudar periodicamente (a cada 5 ou 10 segundos). Usar imagens de Lisboa mas também imagens de edições anteriores (CETC2013 e CETC2011). A ideia é mostrar um pouco da história e da continuidade. O Alessandro tem estas fotos.

2 - Colocar uma referência para o site de submissão (por agora basta dizer que se usará o EasyChair); quando o site estiver mesmo publicado, eu tratarei do site de submissão.

**Comment by fmcarvalho** [comment]
Concordo com o ponto 1. 

@arturj Arranjas as fotos?

@ruimfjesus Escolhes o plugin para o carrossel ?

**Comment by ruimfjesus** [comment]
A mulher do Fantoni trabalha em fotografia e vai arranjar cerca de 10 foto
de Lisboa.
Sim, tenho o código em JavaScript que faz o carrossel.

Eu concordo que devemos ter um carrossel de fotos sobre lisboa e edições
anteriores mas não sei se fica bem na imagem do banner.

Rui Jesus

On Wed, Mar 11, 2015 at 3:57 PM, Fernando Miguel Carvalho <
notifications@github.com> wrote:

> Concordo com o ponto 1.
> 
> @arturj https://github.com/arturj Arranjas as fotos?
> 
> @ruimfjesus https://github.com/ruimfjesus Escolhes o plugin para o
> carrossel ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetc2016/cetc2016.github.io/issues/4#issuecomment-78292520
> .

## 

Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219

**Comment by fmcarvalho** [comment]
Acho que é uma questão de experimentar. Depende também do tipo de fotos. 

@ruimfjesus Para colocar o caroussel teremos que substituir `<section id="banner_bmenu"></section>` pelo `<span class="banner"><img src="images/banner.jpg" alt="" /></span>` no ficheiro de [layout](https://github.com/cetc2016/cetc2016.github.io/blob/master/_layouts/default.html).

Experimentei mas a imagem já NÃO fica a ocupar toda a largura da página. Não gostei tanto. É preciso descobrir qual a class CSS que mantém aquele banner a toda a largura.

**Comment by ruimfjesus** [comment]
Olá,

Não tenho tido tempo para ver isto. Vou ver e depois digo alguma coisa.

2015-03-12 14:54 GMT+00:00 Fernando Miguel Carvalho <
notifications@github.com>:

> Acho que é uma questão de experimentar. Depende também do tipo de fotos.
> 
> @ruimfjesus https://github.com/ruimfjesus Para colocar o caroussel
> teremos que substituir pelo http://images/banner.jpg no ficheiro de
> layout
> https://github.com/cetc2016/cetc2016.github.io/blob/master/_layouts/default.html
> .
> 
> Experimentei mas a imagem já NÃO fica a ocupar toda a largura da página.
> Não gostei tanto. É preciso descobrir qual a class CSS que mantém aquele
> banner a toda a largura.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetc2016/cetc2016.github.io/issues/4#issuecomment-78495604
> .

## 

Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219
