### ISSUE TITLE
Inportant Dates --- Qual se remove?

### ISSUE THREAD

**Issue by fmcarvalho** [cetc2016/cetc2016.github.io#5]
3 - Qual a diferença entre "Dates" que está na entrada "CETC2016" e "Important Dates" que está na entrada "Call For Papers"?

**Comment by fmcarvalho** [comment]
Nenhuma. Digam qual querem remover? @cvaz @ruimfjesus

**Comment by ruimfjesus** [comment]
Na reunião falamos sobre este ponto.
A Manuela Vieira achou que estava bem "Program"
Eu acho que está bem Program. Não concordo com o Artur

On Wed, Mar 11, 2015 at 3:57 PM, Fernando Miguel Carvalho <
notifications@github.com> wrote:

> Nenhuma. Digam qual querem remover? @cvaz <https://github.com/cvaz>
> @ruimfjesus <https://github.com/ruimfjesus>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cetc2016/cetc2016.github.io/issues/5#issuecomment-78292647>
> .
>



-- 
Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219

**Comment by cvaz** [comment]
Não há nenhuma. Eu penso que deveria ficar apenas no Call For Papers

**Comment by fmcarvalho** [comment]
Segui então a sugestão da @cvaz
