### ISSUE TITLE
Sugestões de melhoria ao texto

### ISSUE THREAD

**Issue by fmcarvalho** [cetc2016/cetc2016.github.io#6]
6 - Em vez de "Attending" ficaria melhor "Venue".

9- A designação (ISEL-ADEETC) após cada nome dos membros do comité organizador é cansativa e redundante. Poderá ser 
colocada uma só vez no início ou no final da lista.

**Comment by fmcarvalho** [comment]
@cvaz @ruimfjesus concordam?

**Comment by ruimfjesus** [comment]
Não. Acho que fica melhor Attending.
Rui Jesus

On Wed, Mar 11, 2015 at 3:58 PM, Fernando Miguel Carvalho <
notifications@github.com> wrote:

> @cvaz https://github.com/cvaz @ruimfjesus
> https://github.com/ruimfjesus concordam?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetc2016/cetc2016.github.io/issues/6#issuecomment-78292725
> .

## 

Rui Manuel Feliciano de Jesus
Prof. Adjunto
Área Departamental de Electrónica e Telecomunicações e de Computadores
(ADEETC)
Edifício F, Sala 19
Instituto Superior de Engenharia de Lisboa (ISEL)
Rua Conselheiro Emídio Navarro nº 1 1949-007 LISBOA
Tel. : +351 21 8317 219

**Comment by ruimfjesus** [comment]
Concordo com o ponto 9.

**Comment by cvaz** [comment]
Sim, é um pouco repetitiva. No entanto, esse mesmo problema vai aparecer no cientific comité... não sei.

É me indiferente attending ou venue.
