### ISSUE TITLE
Repetição do título de Menu no Topo da página

### ISSUE THREAD

**Issue by fmcarvalho** [cetc2016/cetc2016.github.io#7]
Cada página começa com o Título igual ao que está seleccionado no Menu. Sugiro remover este título do topo da página? Concordam?

**Comment by ruimfjesus** [comment]
Sim. 
Mas deve-se manter o subtitulo, isto é, a opção escolhida no menu dropdown

**Comment by fmcarvalho** [comment]
Sim, concordo @ruimfjesus

**Comment by fmcarvalho** [comment]
Done
